### ISSUE TITLE
Bump crates.io version

### ISSUE THREAD

**Issue by felix91gr** [jrozner/synfuzz#5]
I had problems when trying to use this from the crates.io index. I figured out that it's due to a mismatch in the published version number v/s the real version number. If you look at the [crate manifest](https://github.com/jrozner/synfuzz/blob/master/synfuzz/Cargo.toml), you'll see a clear `0.1.0` version number. However, at the [crate entry at the index](https://crates.io/crates/synfuzz), the given version number is `0.0.0`. 

This mismatch doesn't allow `cargo` to function properly. A small change to the published version number should be enough, though :)

**Comment by jrozner** [comment]
I should be back to a computer within the next day or two and can take care of this.

**Comment by jrozner** [comment]
A release tag has been created and a new version published to crates.
